site_name: Simulación de circutos con herramientas open source
site_dir: build
markdown_extensions:
  - admonition #https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - attr_list

# use_directory_urls: false
plugins:
  - search
#  - pdf-export:
#      combined: true

# lang: es

theme:
  name: 'readthedocs' # 'mkdocs' 'material'
  highlightjs: false # true/false false para prueba sin internet
  hljs_languages:
    - javascript
    - python
    - lua
    - c
    - c++
    - bash


extra_css: [extra.css] # Active this (uncomment) if you have external css in docs/extra.css

nav:
   - Home: index.md
   - Instalación de herramientas: install.md
   - Básicos:
       - Divisor de voltaje: ./basic/voltage-divider/README.md
       - Divisor de corriente: ./basic/current-divider/README.md
       - Circuito RC sin fuente: ./basic/rc-circuit-without-source/README.md

